# This is a basic workflow to help you get started with Actions

name: DigitalOceanCI

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  push:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - name: Fetching repository gkshi/youtrack
        uses: actions/checkout@v1
        with:
          ssh-key: ${{ secrets.DIGITAL_OCEAN_SSHKEY }}

      - name: Cloning repo files via scp
        uses: appleboy/scp-action@master
        env:
          HOST: ${{ secrets.DIGITAL_OCEAN_HOST }}
          USERNAME: ${{ secrets.DIGITAL_OCEAN_USERNAME }}
          PORT: ${{ secrets.DIGITAL_OCEAN_PORT }}
          KEY: ${{ secrets.DIGITAL_OCEAN_SSHKEY }}
        with:
          host: ${{ secrets.DIGITAL_OCEAN_HOST }}
          username: ${{ secrets.DIGITAL_OCEAN_USERNAME }}
          port: ${{ secrets.DIGITAL_OCEAN_PORT }}
          key: ${{ secrets.DIGITAL_OCEAN_SSHKEY }}
          passphrase: ""
          source: "."
          target: "/var/www/html/vue/app"
          overwrite: true

      - name: Building and starting app
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.DIGITAL_OCEAN_HOST }}
          username: ${{ secrets.DIGITAL_OCEAN_USERNAME }}
          port: ${{ secrets.DIGITAL_OCEAN_PORT }}
          key: ${{ secrets.DIGITAL_OCEAN_SSHKEY }}
          passphrase: ""
          script: /var/www/deploy.sh
