# This is a basic workflow to help you get started with Actions

name: DigitalOceanCI

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  push:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@master

    - name: Copying files via scp
      uses: appleboy/scp-action@master
      with:
        host: ${{ secrets.DIGITAL_OCEAN_HOST }}
        username: ${{ secrets.DIGITAL_OCEAN_USERNAME }}
        port: ${{ secrets.DIGITAL_OCEAN_PORT }}
        key: ${{ secrets.DIGITAL_OCEAN_SSHKEY }}
        passphrase: ""
        source: "."
        target: "/var/www/html/vue/app"

    - name: Executing remote  command
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.DIGITAL_OCEAN_HOST }}
        username: ${{ secrets.DIGITAL_OCEAN_USERNAME }}
        port: ${{ secrets.DIGITAL_OCEAN_PORT }}
        key: ${{ secrets.DIGITAL_OCEAN_SSHKEY }}
        passphrase: ""
        script: /var/www/deploy.sh
