# This is a basic workflow to help you get started with Actions

name: DigitalOceanCI

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  push:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
      
    - name: Copy file via scp
      uses: appleboy/scp-action@master
      env:
        HOST: ${{ secrets.DIGITAL_OCEAN_HOST }}
        USERNAME: ${{ secrets.DIGITAL_OCEAN_USERNAME }}
        PORT: ${{ secrets.DIGITAL_OCEAN_PORT }}
        KEY: ${{ secrets.DIGITAL_OCEAN_SSHKEY }}
      with:
        source: "."
        target: "/var/www/html/vue/app"

    - name: Executing remote  command
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.DIGITAL_OCEAN_HOST }}
        USERNAME: ${{ secrets.DIGITAL_OCEAN_USERNAME }}
        PORT: ${{ secrets.DIGITAL_OCEAN_PORT }}
        KEY: ${{ secrets.DIGITAL_OCEAN_SSHKEY }}
        script: /var/www/deploy.sh
